checking 2

diff --git a/.github/workflows/buildandtest.yml b/.github/workflows/buildandtest.yml
--- a/.github/workflows/buildandtest.yml
+++ b/.github/workflows/buildandtest.yml
@@ -22,3 +22,10 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --no-build --verbosity normal --logger trx
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: TRX results
+        path: TestResults/*.trx    # Path to test results
+        reporter: dotnet-trx
